package ticTac.Connection;

enum msgType {
  SIGNIN,
  SIGNUP,
  GET_LEADERBOARD,
  GET_ONLINE_PLAYERS,
  CLOSE_CONNECTION,
  INVETATION_SEND,
  INVETATION_REPLY,
  START_GAME,
  ADD_MOVE,
  SEND_MESSAGE,
  SAVE_DONE_GAME,
  REPLAY_ASK,
  REPLAY_REPLY,
  RECORD_GAME,
  GET_RECORDED_GAMES,
  GET_ALL_PLAYERS,
  RESUME_GAME_SEND,
  RESUME_GAME_REPLY
}
